/****** Object:  StoredProcedure [dbo].[GetCO2Year]    Script Date: 08/31/2014 21:53:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GetCO2Year]
AS
BEGIN
	--当年第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0)
	--获取当年的碳排量
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)*0.785
	FROM ConsumptionData C
	WHERE DeviceID=388 AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
	
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0
	
	SELECT @TOTAL
	
END
GO
/****** Object:  StoredProcedure [dbo].[GetCO2Mouth]    Script Date: 08/31/2014 21:57:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GetCO2Mouth]
AS
BEGIN
	--当月第一天
	DECLARE @DAY_MOUTH DATETIME
	SET @DAY_MOUTH = CONVERT(VARCHAR(100), DATEADD(dd,-DAY(GETDATE())+1,GETDATE()),23)
	--获取一个月的碳排量
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)*0.785
	FROM ConsumptionData C
	WHERE DeviceID=388 AND ReadingDate BETWEEN @DAY_MOUTH AND GETDATE()
	--过滤为空
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0
	SELECT @TOTAL
END
/****** Object:  StoredProcedure [dbo].[GetUtilities]    Script Date: 08/31/2014 21:58:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得今年的水电气
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilities]
	@DeviceID INT
AS
BEGIN
	--今年第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0)
	--获取水电气
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
		IF @TOTAL IS NULL
			SET @TOTAL = 0.0
		
	SELECT @TOTAL
		
END
GO
/****** Object:  StoredProcedure [dbo].[GetUtilitiesEnergy]    Script Date: 08/31/2014 21:58:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--能源消费明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesEnergy]
	@DeviceID INT
AS
BEGIN
	--今天
	DECLARE @DAY_TODAY DATETIME
	SET @DAY_TODAY = CONVERT(VARCHAR(100), DATEADD(dd,-DAY(GETDATE())+1,GETDATE()),23)
	--本周一
	DECLARE @DAY_WEEK DATETIME
	DECLARE @WEEKDAY INT
	SET @WEEKDAY = DATEPART(weekday,GETDATE())
	IF @WEEKDAY = 1
	BEGIN
		SET @DAY_WEEK = DATEADD(wk,DATEDIFF(wk,7,getdate()),0)    
	END
	ELSE
		SET @DAY_WEEK = DATEADD(wk,DATEDIFF(wk,0,GETDATE()),0)   
	--当月的第一天
	DECLARE @DAY_MONTH DATETIME
	SET @DAY_MONTH = DATEADD(mm, DATEDIFF(mm,0,DATEADD(mm, 0, GETDATE())), 0) 
	--当年的第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = DATEADD(yy, DATEDIFF(yy,0,DATEADD(yy, 0, GETDATE())), 0)  	
	
	DECLARE @TOTAL_TODAY FLOAT
	DECLARE @TOTAL_WEEK FLOAT
	DECLARE @TOTAL_MONTH FLOAT
	DECLARE @TOTAL_YEAR FLOAT
	
	--Today
	SELECT @TOTAL_TODAY = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_TODAY AND GETDATE()
	IF @TOTAL_TODAY IS NULL
		SET @TOTAL_TODAY = 0
	--Week
	SELECT @TOTAL_WEEK = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_WEEK AND GETDATE()
	IF @TOTAL_WEEK IS NULL
		SET @TOTAL_WEEK = 0
	--Month
	SELECT @TOTAL_MONTH = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_MONTH AND GETDATE()
	IF @TOTAL_MONTH IS NULL
		SET @TOTAL_MONTH = 0
	--Year
	SELECT @TOTAL_YEAR = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
	IF @TOTAL_YEAR IS NULL
		SET @TOTAL_YEAR = 0
		
	SELECT @TOTAL_TODAY AS 'Today',
	@TOTAL_WEEK AS 'WTD',
	@TOTAL_MONTH AS 'MTD',
	@TOTAL_YEAR AS 'YTD'
END
Go
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrev]    Script Date: 08/31/2014 21:58:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得去年的水电气
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrev]
	@DeviceID INT
AS
BEGIN
	--去年第一天
	DECLARE @DAY_YEAR_F DATETIME
	SET @DAY_YEAR_F = DATEADD(yy, DATEDIFF(yy,0,GETDATE())-1, 0)
	--去年最后一天
	DECLARE @DAY_YEAR_L DATETIME
	SET @DAY_YEAR_L = DATEADD(ms,-3,DATEADD(yy, DATEDIFF(yy,0,getdate()), 0))  
	--获取水电气
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR_F AND @DAY_YEAR_L
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0	
	SELECT @TOTAL
END
GO
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrevMonths]    Script Date: 08/31/2014 21:59:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得去年12个月的水电气明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrevMonths]
	@DeviceID INT
AS
BEGIN
	--获得每个月第一天和最后一天
	DECLARE @MOUTH_1_F DATETIME
	DECLARE @MOUTH_1_L DATETIME
	DECLARE @MOUTH_2_F DATETIME
	DECLARE @MOUTH_2_L DATETIME
	DECLARE @MOUTH_3_F DATETIME
	DECLARE @MOUTH_3_L DATETIME
	DECLARE @MOUTH_4_F DATETIME
	DECLARE @MOUTH_4_L DATETIME
	DECLARE @MOUTH_5_F DATETIME
	DECLARE @MOUTH_5_L DATETIME
	DECLARE @MOUTH_6_F DATETIME
	DECLARE @MOUTH_6_L DATETIME
	DECLARE @MOUTH_7_F DATETIME
	DECLARE @MOUTH_7_L DATETIME
	DECLARE @MOUTH_8_F DATETIME
	DECLARE @MOUTH_8_L DATETIME
	DECLARE @MOUTH_9_F DATETIME
	DECLARE @MOUTH_9_L DATETIME
	DECLARE @MOUTH_10_F DATETIME
	DECLARE @MOUTH_10_L DATETIME
	DECLARE @MOUTH_11_F DATETIME
	DECLARE @MOUTH_11_L DATETIME
	DECLARE @MOUTH_12_F DATETIME
	DECLARE @MOUTH_12_L DATETIME
	
	SET @MOUTH_1_F = DATEADD(yy, DATEDIFF(yy,0,GETDATE())-1, 0)--去年第一天
	SET @MOUTH_2_F = DATEADD(mm,1,@MOUTH_1_F)
	SET @MOUTH_3_F = DATEADD(mm,2,@MOUTH_1_F)
	SET @MOUTH_4_F = DATEADD(mm,3,@MOUTH_1_F)
	SET @MOUTH_5_F = DATEADD(mm,4,@MOUTH_1_F)
	SET @MOUTH_6_F = DATEADD(mm,5,@MOUTH_1_F)
	SET @MOUTH_7_F = DATEADD(mm,6,@MOUTH_1_F)
	SET @MOUTH_8_F = DATEADD(mm,7,@MOUTH_1_F)
	SET @MOUTH_9_F = DATEADD(mm,8,@MOUTH_1_F)
	SET @MOUTH_10_F = DATEADD(mm,9,@MOUTH_1_F)
	SET @MOUTH_11_F = DATEADD(mm,10,@MOUTH_1_F)
	SET @MOUTH_12_F = DATEADD(mm,11,@MOUTH_1_F)
	SET @MOUTH_1_L = DATEADD(ms,-3,DATEADD(dd, DATEDIFF(dd,@MOUTH_1_F,@MOUTH_2_F), @MOUTH_1_F))
	SET @MOUTH_2_L = DATEADD(mm,1,@MOUTH_1_L)
	SET @MOUTH_3_L = DATEADD(mm,2,@MOUTH_1_L)
	SET @MOUTH_4_L = DATEADD(mm,3,@MOUTH_1_L)
	SET @MOUTH_5_L = DATEADD(mm,4,@MOUTH_1_L)
	SET @MOUTH_6_L = DATEADD(mm,5,@MOUTH_1_L)
	SET @MOUTH_7_L = DATEADD(mm,6,@MOUTH_1_L)
	SET @MOUTH_8_L = DATEADD(mm,7,@MOUTH_1_L)
	SET @MOUTH_9_L = DATEADD(mm,8,@MOUTH_1_L)
	SET @MOUTH_10_L = DATEADD(mm,9,@MOUTH_1_L)
	SET @MOUTH_11_L = DATEADD(mm,10,@MOUTH_1_L)
	SET @MOUTH_12_L = DATEADD(mm,11,@MOUTH_1_L)
	
	--获取每个月的水电气
	DECLARE @TOTAL_1 FLOAT
	SELECT @TOTAL_1 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_1_F AND @MOUTH_1_L
	IF @TOTAL_1 IS NULL
		SET @TOTAL_1 = 0.0
		
	DECLARE @TOTAL_2 FLOAT
	SELECT @TOTAL_2 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_2_F AND @MOUTH_2_L
	IF @TOTAL_2 IS NULL
		SET @TOTAL_2 = 0.0
	
	DECLARE @TOTAL_3 FLOAT
	SELECT @TOTAL_3 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_3_F AND @MOUTH_3_L
	IF @TOTAL_3 IS NULL
		SET @TOTAL_3 = 0.0
	
	DECLARE @TOTAL_4 FLOAT
	SELECT @TOTAL_4 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_4_F AND @MOUTH_4_L
	IF @TOTAL_4 IS NULL
		SET @TOTAL_4 = 0.0
			
	DECLARE @TOTAL_5 FLOAT
	SELECT @TOTAL_5 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_5_F AND @MOUTH_5_L
	IF @TOTAL_5 IS NULL
		SET @TOTAL_5 = 0.0
			
	DECLARE @TOTAL_6 FLOAT
	SELECT @TOTAL_6 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_6_F AND @MOUTH_6_L
	IF @TOTAL_6 IS NULL
		SET @TOTAL_6 = 0.0
	
	DECLARE @TOTAL_7 FLOAT
	SELECT @TOTAL_7 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_7_F AND @MOUTH_7_L
	IF @TOTAL_7 IS NULL
		SET @TOTAL_7 = 0.0
			
	DECLARE @TOTAL_8 FLOAT
	SELECT @TOTAL_8 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_8_F AND @MOUTH_8_L
	IF @TOTAL_8 IS NULL
		SET @TOTAL_8 = 0.0
	
	DECLARE @TOTAL_9 FLOAT
	SELECT @TOTAL_9 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_9_F AND @MOUTH_9_L
	IF @TOTAL_9 IS NULL
		SET @TOTAL_9 = 0.0
			
	DECLARE @TOTAL_10 FLOAT
	SELECT @TOTAL_10 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_10_F AND @MOUTH_10_L
	IF @TOTAL_10 IS NULL
		SET @TOTAL_10 = 0.0
	
	DECLARE @TOTAL_11 FLOAT
	SELECT @TOTAL_11 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_11_F AND @MOUTH_11_L
	IF @TOTAL_11 IS NULL
		SET @TOTAL_11 = 0.0
			
	DECLARE @TOTAL_12 FLOAT
	SELECT @TOTAL_12 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_12_F AND @MOUTH_12_L
	IF @TOTAL_12 IS NULL
		SET @TOTAL_12 = 0.0
	
	--Select		
	SELECT @TOTAL_1,
	@TOTAL_2,
	@TOTAL_3,
	@TOTAL_4,
	@TOTAL_5,
	@TOTAL_6,
	@TOTAL_7,
	@TOTAL_8,
	@TOTAL_9,
	@TOTAL_10,
	@TOTAL_11,
	@TOTAL_12 
END
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrevDays]    Script Date: 08/31/2014 21:58:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得12个月的水电气明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrevDays]
	@DeviceID	INT
AS
BEGIN
	--获得每个月第一天和最后一天
	DECLARE @MOUTH_1_F DATETIME
	DECLARE @MOUTH_1_L DATETIME
	DECLARE @MOUTH_2_F DATETIME
	DECLARE @MOUTH_2_L DATETIME
	DECLARE @MOUTH_3_F DATETIME
	DECLARE @MOUTH_3_L DATETIME
	DECLARE @MOUTH_4_F DATETIME
	DECLARE @MOUTH_4_L DATETIME
	DECLARE @MOUTH_5_F DATETIME
	DECLARE @MOUTH_5_L DATETIME
	DECLARE @MOUTH_6_F DATETIME
	DECLARE @MOUTH_6_L DATETIME
	DECLARE @MOUTH_7_F DATETIME
	DECLARE @MOUTH_7_L DATETIME
	DECLARE @MOUTH_8_F DATETIME
	DECLARE @MOUTH_8_L DATETIME
	DECLARE @MOUTH_9_F DATETIME
	DECLARE @MOUTH_9_L DATETIME
	DECLARE @MOUTH_10_F DATETIME
	DECLARE @MOUTH_10_L DATETIME
	DECLARE @MOUTH_11_F DATETIME
	DECLARE @MOUTH_11_L DATETIME
	DECLARE @MOUTH_12_F DATETIME
	DECLARE @MOUTH_12_L DATETIME
	
	SET @MOUTH_1_F = DATEADD(yy, DATEDIFF(yy,0,GETDATE())-1, 0)
	SET @MOUTH_2_F = DATEADD(mm,1,@MOUTH_1_F)
	SET @MOUTH_3_F = DATEADD(mm,2,@MOUTH_1_F)
	SET @MOUTH_4_F = DATEADD(mm,3,@MOUTH_1_F)
	SET @MOUTH_5_F = DATEADD(mm,4,@MOUTH_1_F)
	SET @MOUTH_6_F = DATEADD(mm,5,@MOUTH_1_F)
	SET @MOUTH_7_F = DATEADD(mm,6,@MOUTH_1_F)
	SET @MOUTH_8_F = DATEADD(mm,7,@MOUTH_1_F)
	SET @MOUTH_9_F = DATEADD(mm,8,@MOUTH_1_F)
	SET @MOUTH_10_F = DATEADD(mm,9,@MOUTH_1_F)
	SET @MOUTH_11_F = DATEADD(mm,10,@MOUTH_1_F)
	SET @MOUTH_12_F = DATEADD(mm,11,@MOUTH_1_F)
	SET @MOUTH_1_L = DATEADD(ms,-3,DATEADD(dd, DATEDIFF(dd,@MOUTH_1_F,@MOUTH_2_F), @MOUTH_1_F))
	SET @MOUTH_2_L = DATEADD(mm,1,@MOUTH_1_L)
	SET @MOUTH_3_L = DATEADD(mm,2,@MOUTH_1_L)
	SET @MOUTH_4_L = DATEADD(mm,3,@MOUTH_1_L)
	SET @MOUTH_5_L = DATEADD(mm,4,@MOUTH_1_L)
	SET @MOUTH_6_L = DATEADD(mm,5,@MOUTH_1_L)
	SET @MOUTH_7_L = DATEADD(mm,6,@MOUTH_1_L)
	SET @MOUTH_8_L = DATEADD(mm,7,@MOUTH_1_L)
	SET @MOUTH_9_L = DATEADD(mm,8,@MOUTH_1_L)
	SET @MOUTH_10_L = DATEADD(mm,9,@MOUTH_1_L)
	SET @MOUTH_11_L = DATEADD(mm,10,@MOUTH_1_L)
	SET @MOUTH_12_L = DATEADD(mm,11,@MOUTH_1_L)
	
	--获取每个月的水电气
	DECLARE @TOTAL_1 FLOAT
	SELECT @TOTAL_1 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_1_F AND @MOUTH_1_L
	IF @TOTAL_1 IS NULL
		SET @TOTAL_1 = 0.0
		
	DECLARE @TOTAL_2 FLOAT
	SELECT @TOTAL_2 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_2_F AND @MOUTH_2_L
	IF @TOTAL_2 IS NULL
		SET @TOTAL_2 = 0.0
	
	DECLARE @TOTAL_3 FLOAT
	SELECT @TOTAL_3 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_3_F AND @MOUTH_3_L
	IF @TOTAL_3 IS NULL
		SET @TOTAL_3 = 0.0
	
	DECLARE @TOTAL_4 FLOAT
	SELECT @TOTAL_4 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_4_F AND @MOUTH_4_L
	IF @TOTAL_4 IS NULL
		SET @TOTAL_4 = 0.0
			
	DECLARE @TOTAL_5 FLOAT
	SELECT @TOTAL_5 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_5_F AND @MOUTH_5_L
	IF @TOTAL_5 IS NULL
		SET @TOTAL_5 = 0.0
			
	DECLARE @TOTAL_6 FLOAT
	SELECT @TOTAL_6 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_6_F AND @MOUTH_6_L
	IF @TOTAL_6 IS NULL
		SET @TOTAL_6 = 0.0
	
	DECLARE @TOTAL_7 FLOAT
	SELECT @TOTAL_7 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_7_F AND @MOUTH_7_L
	IF @TOTAL_7 IS NULL
		SET @TOTAL_7 = 0.0
			
	DECLARE @TOTAL_8 FLOAT
	SELECT @TOTAL_8 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_8_F AND @MOUTH_8_L
	IF @TOTAL_8 IS NULL
		SET @TOTAL_8 = 0.0
	
	DECLARE @TOTAL_9 FLOAT
	SELECT @TOTAL_9 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_9_F AND @MOUTH_9_L
	IF @TOTAL_9 IS NULL
		SET @TOTAL_9 = 0.0
			
	DECLARE @TOTAL_10 FLOAT
	SELECT @TOTAL_10 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_10_F AND @MOUTH_10_L
	IF @TOTAL_10 IS NULL
		SET @TOTAL_10 = 0.0
	
	DECLARE @TOTAL_11 FLOAT
	SELECT @TOTAL_11 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_11_F AND @MOUTH_11_L
	IF @TOTAL_11 IS NULL
		SET @TOTAL_11 = 0.0
			
	DECLARE @TOTAL_12 FLOAT
	SELECT @TOTAL_12 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_12_F AND @MOUTH_12_L
	IF @TOTAL_12 IS NULL
		SET @TOTAL_12 = 0.0
	
	--Select		
	SELECT @TOTAL_1,
	@TOTAL_2,
	@TOTAL_3,
	@TOTAL_4,
	@TOTAL_5,
	@TOTAL_6,
	@TOTAL_7,
	@TOTAL_8,
	@TOTAL_9,
	@TOTAL_10,
	@TOTAL_11,
	@TOTAL_12 
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GetEquipmentEnergy]
	@DeviceID INT
AS
BEGIN
	--名称
	DECLARE @NAME NVARCHAR(510)
	SELECT @NAME = Name FROM dbo.ListOfDevices WHERE DeviceID = @DeviceID
	--去年第一天和最后一天
	DECLARE @DAY_YEAR_F DATETIME
	DECLARE @DAY_YEAR_L DATETIME
	SET @DAY_YEAR_F = DATEADD(yy, DATEDIFF(yy,0,GETDATE())-1, 0)
	SET @DAY_YEAR_L = DATEADD(ms,-3,DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0))  
	--今年的第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR =DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0)
	--获得四个季度的开始和截止时间
	DECLARE @QUARTER_1_F DATETIME
	DECLARE @QUARTER_1_L DATETIME
	DECLARE @QUARTER_2_F DATETIME
	DECLARE @QUARTER_2_L DATETIME
	DECLARE @QUARTER_3_F DATETIME
	DECLARE @QUARTER_3_L DATETIME
	DECLARE @QUARTER_4_F DATETIME
	DECLARE @QUARTER_4_L DATETIME
	SET @QUARTER_1_F = @DAY_YEAR
	SET @QUARTER_2_F = DATEADD(qq,1,@QUARTER_1_F)
	SET @QUARTER_3_F = DATEADD(qq,1,@QUARTER_2_F)
	SET @QUARTER_4_F = DATEADD(qq,1,@QUARTER_3_F)
	SET @QUARTER_1_L = DATEADD(ms,-3,@QUARTER_2_F)
	SET @QUARTER_2_L = DATEADD(ms,-3,@QUARTER_3_F)
	SET @QUARTER_3_L = DATEADD(ms,-3,@QUARTER_4_F)
	SET @QUARTER_4_L = DATEADD(ms,-3,DATEADD(yy,1,@DAY_YEAR))
	--获得当前季度的3个月
	DECLARE @MONTH_1_F DATETIME
	DECLARE @MONTH_1_L DATETIME
	DECLARE @MONTH_2_F DATETIME
	DECLARE @MONTH_2_L DATETIME
	DECLARE @MONTH_3_F DATETIME
	DECLARE @MONTH_3_L DATETIME
	SET @MONTH_1_F = DATEADD(mm,3*(DATEPART(qq,GETDATE())-1),@DAY_YEAR)
	SET @MONTH_1_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_1_F))
	SET @MONTH_2_F = DATEADD(mm,1,@MONTH_1_F)
	SET @MONTH_2_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_2_F))
	SET @MONTH_3_F = DATEADD(mm,2,@MONTH_1_F)
	SET @MONTH_3_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_3_F))
	--获得当前月的各个星期
	DECLARE @WEEK_1_F DATETIME
	DECLARE @WEEK_1_L DATETIME
	DECLARE @WEEK_2_F DATETIME
	DECLARE @WEEK_2_L DATETIME
	DECLARE @WEEK_3_F DATETIME
	DECLARE @WEEK_3_L DATETIME
	DECLARE @WEEK_4_F DATETIME
	DECLARE @WEEK_4_L DATETIME
	SET @WEEK_1_F = DATEADD(mm, DATEDIFF(m,0,GETDATE()), 0)
	SET @WEEK_1_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_1_F))
	SET @WEEK_2_F = DATEADD(ww, 1, @WEEK_1_F)
	SET @WEEK_2_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_2_F))
	SET @WEEK_3_F = DATEADD(ww, 1, @WEEK_2_F)
	SET @WEEK_3_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_3_F))
	SET @WEEK_4_F = DATEADD(ww, 1, @WEEK_3_F)
	SET @WEEK_4_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_3_F))
	--获得各个时间段的值
	--今年的总数
	DECLARE @TOTAL FLOAT 
	SELECT @TOTAL = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID IN (390,391,392,393,394,395,396,397,398,399,400)
	AND (ReadingDate BETWEEN @DAY_YEAR AND GETDATE())
	
	--Previous Year
	DECLARE @TOTAL1 FLOAT 
	SELECT @TOTAL1 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR_F AND @DAY_YEAR_L
	--Yearly Target
	DECLARE @TOTAL2 FLOAT 
	SET @TOTAL2 = 0.0 --定制目前空着
	--YTD
	DECLARE @TOTAL3 FLOAT 
	SELECT @TOTAL3 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @DAY_YEAR AND GETDATE())
	--%
	DECLARE @TOTAL4 FLOAT 
	SET @TOTAL4 = @TOTAL3/@TOTAL
	--Q1
	DECLARE @TOTAL5 FLOAT 
	SELECT @TOTAL5 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @QUARTER_1_F AND @QUARTER_1_L)
	--Q2
	DECLARE @TOTAL6 FLOAT 
	SELECT @TOTAL6 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @QUARTER_2_F AND @QUARTER_2_L)
	--Q3
	DECLARE @TOTAL7 FLOAT 
	SELECT @TOTAL7 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @QUARTER_3_F AND @QUARTER_3_L)
	--Q4
	DECLARE @TOTAL8 FLOAT 
	SELECT @TOTAL8 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @QUARTER_4_F AND @QUARTER_4_L)
	--Month1
	DECLARE @TOTAL9 FLOAT 
	SELECT @TOTAL9 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @MONTH_1_F AND @MONTH_1_L)
	--Month2
	DECLARE @TOTAL10 FLOAT 
	SELECT @TOTAL10 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @MONTH_2_F AND @MONTH_2_L)
	--Month3
	DECLARE @TOTAL11 FLOAT 
	SELECT @TOTAL11 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @MONTH_3_F AND @MONTH_3_L)
	--Week1
	DECLARE @TOTAL12 FLOAT 
	SELECT @TOTAL12 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @WEEK_1_F AND @WEEK_1_L)
	--Week2
	DECLARE @TOTAL13 FLOAT 
	SELECT @TOTAL13 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @WEEK_2_F AND @WEEK_2_L)
	--Week3
	DECLARE @TOTAL14 FLOAT 
	SELECT @TOTAL14 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @WEEK_3_F AND @WEEK_3_L)
	--Week4
	DECLARE @TOTAL15 FLOAT 
	SELECT @TOTAL15 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND (ReadingDate BETWEEN @WEEK_4_F AND @WEEK_4_L)
	
	SELECT @NAME AS 'Name',
	@TOTAL1 AS 'PreviousYear',
	@TOTAL2 AS 'YearlyTarget',
	@TOTAL3 AS 'YTD',
	@TOTAL4 AS 'Percentage',
	@TOTAL5 AS 'Q1',
	@TOTAL6 AS 'Q2',
	@TOTAL7 AS 'Q3',
	@TOTAL8 AS 'Q4',
	@TOTAL9 AS 'Month1', 
	@TOTAL10 AS 'Month2',
	@TOTAL11 AS 'Month3',
	@TOTAL12 AS 'Week1',
	@TOTAL13 AS 'Week2',
	@TOTAL14 AS 'Week3',
	@TOTAL15 AS 'Week4',
	@TOTAL AS 'TotalYTD'
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得去年的水电气
ALTER PROCEDURE [dbo].[GetAllEquipmentEnergy]
AS
BEGIN
	--去年第一天和最后一天
	DECLARE @DAY_YEAR_F DATETIME
	DECLARE @DAY_YEAR_L DATETIME
	SET @DAY_YEAR_F = DATEADD(yy, DATEDIFF(yy,0,GETDATE())-1, 0)
	SET @DAY_YEAR_L = DATEADD(ms,-3,DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0))  
	--今年的第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR =DATEADD(yy, DATEDIFF(yy,0,GETDATE()), 0)
	--获得四个季度的开始和截止时间
	DECLARE @QUARTER_1_F DATETIME
	DECLARE @QUARTER_1_L DATETIME
	DECLARE @QUARTER_2_F DATETIME
	DECLARE @QUARTER_2_L DATETIME
	DECLARE @QUARTER_3_F DATETIME
	DECLARE @QUARTER_3_L DATETIME
	DECLARE @QUARTER_4_F DATETIME
	DECLARE @QUARTER_4_L DATETIME
	SET @QUARTER_1_F = @DAY_YEAR
	SET @QUARTER_2_F = DATEADD(qq,1,@QUARTER_1_F)
	SET @QUARTER_3_F = DATEADD(qq,1,@QUARTER_2_F)
	SET @QUARTER_4_F = DATEADD(qq,1,@QUARTER_3_F)
	SET @QUARTER_1_L = DATEADD(ms,-3,@QUARTER_2_F)
	SET @QUARTER_2_L = DATEADD(ms,-3,@QUARTER_3_F)
	SET @QUARTER_3_L = DATEADD(ms,-3,@QUARTER_4_F)
	SET @QUARTER_4_L = DATEADD(ms,-3,DATEADD(yy,1,@DAY_YEAR))
	--获得当前季度的3个月
	DECLARE @MONTH_1_F DATETIME
	DECLARE @MONTH_1_L DATETIME
	DECLARE @MONTH_2_F DATETIME
	DECLARE @MONTH_2_L DATETIME
	DECLARE @MONTH_3_F DATETIME
	DECLARE @MONTH_3_L DATETIME
	SET @MONTH_1_F = DATEADD(mm,3*(DATEPART(qq,GETDATE())-1),@DAY_YEAR)
	SET @MONTH_1_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_1_F))
	SET @MONTH_2_F = DATEADD(mm,1,@MONTH_1_F)
	SET @MONTH_2_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_2_F))
	SET @MONTH_3_F = DATEADD(mm,2,@MONTH_1_F)
	SET @MONTH_3_L = DATEADD(ms,-3,DATEADD(mm,1,@MONTH_3_F))
	--获得当前月的各个星期
	DECLARE @WEEK_1_F DATETIME
	DECLARE @WEEK_1_L DATETIME
	DECLARE @WEEK_2_F DATETIME
	DECLARE @WEEK_2_L DATETIME
	DECLARE @WEEK_3_F DATETIME
	DECLARE @WEEK_3_L DATETIME
	DECLARE @WEEK_4_F DATETIME
	DECLARE @WEEK_4_L DATETIME
	SET @WEEK_1_F = DATEADD(mm, DATEDIFF(m,0,GETDATE()), 0)
	SET @WEEK_1_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_1_F))
	SET @WEEK_2_F = DATEADD(ww, 1, @WEEK_1_F)
	SET @WEEK_2_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_2_F))
	SET @WEEK_3_F = DATEADD(ww, 1, @WEEK_2_F)
	SET @WEEK_3_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_3_F))
	SET @WEEK_4_F = DATEADD(ww, 1, @WEEK_3_F)
	SET @WEEK_4_L = DATEADD(ms,-3,DATEADD(ww,1,@WEEK_3_F))
	--声明表变量
	DECLARE @TEMP_ENERGY TABLE(
		Name VARCHAR(510),
		PreviousYear FLOAT,
		YearlyTarget FLOAT,
		YTD FLOAT,
		Percentage FLOAT,
		Q1 FLOAT,
		Q2 FLOAT,
		Q3 FLOAT,
		Q4 FLOAT,
		Month1 FLOAT,
		Month2 FLOAT,
		Month3 FLOAT,
		Week1 FLOAT,
		Week2 FLOAT,
		Week3 FLOAT,
		Week4 FLOAT,
		TotalYTD FLOAT 
	)
	--获得各个时间段的值
	DECLARE @TABLE TABLE(T INT)
	INSERT INTO @TABLE(T) VALUES(390)
	INSERT INTO @TABLE(T) VALUES(391)
	INSERT INTO @TABLE(T) VALUES(392)
	INSERT INTO @TABLE(T) VALUES(393)
	INSERT INTO @TABLE(T) VALUES(394)
	INSERT INTO @TABLE(T) VALUES(395)
	INSERT INTO @TABLE(T) VALUES(396)
	INSERT INTO @TABLE(T) VALUES(397)
	INSERT INTO @TABLE(T) VALUES(398)
	INSERT INTO @TABLE(T) VALUES(399)
	INSERT INTO @TABLE(T) VALUES(400)
	
	--今年的总数
	DECLARE @TOTAL FLOAT 
	SELECT @TOTAL = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID IN (390,391,392,393,394,395,396,397,398,399,400)
	AND (ReadingDate BETWEEN @DAY_YEAR AND GETDATE())
	--声明变量
	DECLARE @SUM_TOTAL_1 FLOAT
	DECLARE @SUM_TOTAL_2 FLOAT
	DECLARE @SUM_TOTAL_3 FLOAT
	DECLARE @SUM_TOTAL_5 FLOAT
	DECLARE @SUM_TOTAL_6 FLOAT
	DECLARE @SUM_TOTAL_7 FLOAT
	DECLARE @SUM_TOTAL_8 FLOAT
	DECLARE @SUM_TOTAL_9 FLOAT
	DECLARE @SUM_TOTAL_10 FLOAT
	DECLARE @SUM_TOTAL_11 FLOAT
	DECLARE @SUM_TOTAL_12 FLOAT
	DECLARE @SUM_TOTAL_13 FLOAT
	DECLARE @SUM_TOTAL_14 FLOAT
	DECLARE @SUM_TOTAL_15 FLOAT
	SET @SUM_TOTAL_1 = 0
	SET @SUM_TOTAL_2 = 0
	SET @SUM_TOTAL_3 = 0
	SET @SUM_TOTAL_5 = 0
	SET @SUM_TOTAL_6 = 0
	SET @SUM_TOTAL_7 = 0
	SET @SUM_TOTAL_8 = 0
	SET @SUM_TOTAL_9 = 0
	SET @SUM_TOTAL_10 = 0
	SET @SUM_TOTAL_11 = 0
	SET @SUM_TOTAL_12 = 0
	SET @SUM_TOTAL_13 = 0
	SET @SUM_TOTAL_14 = 0
	SET @SUM_TOTAL_15 = 0
	--循环ID表
	DECLARE @ID INT
	DECLARE CURSOR1 CURSOR FOR SELECT * FROM @TABLE
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @ID
	WHILE (@@fetch_status=0)
	BEGIN
		--NAME
		DECLARE @NAME NVARCHAR(510)
		SELECT @NAME = Name FROM dbo.ListOfDevices WHERE DeviceID = @ID
		--Previous Year
		DECLARE @TOTAL1 FLOAT 
		SELECT @TOTAL1 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @DAY_YEAR_F AND @DAY_YEAR_L)
		IF @TOTAL1 IS NULL 
			SET @TOTAL1 = 0
		SET @SUM_TOTAL_1 = @SUM_TOTAL_1+@TOTAL1
		--Yearly Target
		DECLARE @TOTAL2 FLOAT 
		SET @TOTAL2 = 0.0 --定制目前空着
		SET @SUM_TOTAL_2 = 0.0
		--YTD
		DECLARE @TOTAL3 FLOAT 
		SELECT @TOTAL3 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @DAY_YEAR AND GETDATE())
		IF @TOTAL3 IS NULL 
			SET @TOTAL3 = 0
		SET @SUM_TOTAL_3 = @SUM_TOTAL_3+@TOTAL3
		--%
		DECLARE @TOTAL4 FLOAT 
		IF @TOTAL IS NULL
			SET @TOTAL4 = 0
		ELSE
			SET @TOTAL4 = @TOTAL3/@TOTAL
		--Q1
		DECLARE @TOTAL5 FLOAT 
		SELECT @TOTAL5 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @QUARTER_1_F AND @QUARTER_1_L)
		IF @TOTAL5 IS NULL 
			SET @TOTAL5 = 0
		SET @SUM_TOTAL_5 = @SUM_TOTAL_5+@TOTAL5
		--Q2
		DECLARE @TOTAL6 FLOAT 
		SELECT @TOTAL6 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @QUARTER_2_F AND @QUARTER_2_L)
		IF @TOTAL6 IS NULL 
			SET @TOTAL6 = 0
		SET @SUM_TOTAL_6 = @SUM_TOTAL_6+@TOTAL6
		--Q3
		DECLARE @TOTAL7 FLOAT 
		SELECT @TOTAL7 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @QUARTER_3_F AND @QUARTER_3_L)
		IF @TOTAL7 IS NULL 
			SET @TOTAL7 = 0
		SET @SUM_TOTAL_7 = @SUM_TOTAL_7+@TOTAL7
		--Q4
		DECLARE @TOTAL8 FLOAT 
		SELECT @TOTAL8 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @QUARTER_4_F AND @QUARTER_4_L)
		IF @TOTAL8 IS NULL 
			SET @TOTAL8 = 0
		SET @SUM_TOTAL_8 = @SUM_TOTAL_8+@TOTAL8
		--Month1
		DECLARE @TOTAL9 FLOAT 
		SELECT @TOTAL9 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @MONTH_1_F AND @MONTH_1_L)
		IF @TOTAL9 IS NULL 
			SET @TOTAL9 = 0
		SET @SUM_TOTAL_9 = @SUM_TOTAL_9+@TOTAL9
		--Month2
		DECLARE @TOTAL10 FLOAT 
		SELECT @TOTAL10 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @MONTH_2_F AND @MONTH_2_L)
		IF @TOTAL10 IS NULL 
			SET @TOTAL10 = 0
		SET @SUM_TOTAL_10 = @SUM_TOTAL_10+@TOTAL10
		--Month3
		DECLARE @TOTAL11 FLOAT 
		SELECT @TOTAL11 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @MONTH_3_F AND @MONTH_3_L)
		IF @TOTAL11 IS NULL 
			SET @TOTAL11 = 0
		SET @SUM_TOTAL_11 = @SUM_TOTAL_11+@TOTAL11
		--Week1
		DECLARE @TOTAL12 FLOAT 
		SELECT @TOTAL12 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @WEEK_1_F AND @WEEK_1_L)
		IF @TOTAL12 IS NULL 
			SET @TOTAL12 = 0
		SET @SUM_TOTAL_12 = @SUM_TOTAL_12+@TOTAL12
		--Week2
		DECLARE @TOTAL13 FLOAT 
		SELECT @TOTAL13 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @WEEK_2_F AND @WEEK_2_L)
		IF @TOTAL13 IS NULL 
			SET @TOTAL13 = 0
		SET @SUM_TOTAL_13 = @SUM_TOTAL_13+@TOTAL13
		--Week3
		DECLARE @TOTAL14 FLOAT 
		SELECT @TOTAL14 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @WEEK_3_F AND @WEEK_3_L)
		IF @TOTAL14 IS NULL 
			SET @TOTAL14 = 0
		SET @SUM_TOTAL_14 = @SUM_TOTAL_14+@TOTAL14
		--Week4
		DECLARE @TOTAL15 FLOAT 
		SELECT @TOTAL15 = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID = @ID
		AND (ReadingDate BETWEEN @WEEK_4_F AND @WEEK_4_L)
		IF @TOTAL15 IS NULL 
			SET @TOTAL15 = 0
		SET @SUM_TOTAL_15 = @SUM_TOTAL_15+@TOTAL15
		
		INSERT INTO @TEMP_ENERGY VALUES(@NAME,
		@TOTAL1,
		@TOTAL2,
		@TOTAL3,
		@TOTAL4,
		@TOTAL5,
		@TOTAL6,
		@TOTAL7,
		@TOTAL8,
		@TOTAL9,
		@TOTAL10,
		@TOTAL11,
		@TOTAL12,
		@TOTAL13,
		@TOTAL14,
		@TOTAL15,
		0)
		
		FETCH NEXT FROM CURSOR1 INTO @ID
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1
	DELETE @TABLE
		
	INSERT INTO @TEMP_ENERGY VALUES('Total',
	@SUM_TOTAL_1,
	@SUM_TOTAL_2,
	@SUM_TOTAL_3,
	0,
	@SUM_TOTAL_5,
	@SUM_TOTAL_6,
	@SUM_TOTAL_7,
	@SUM_TOTAL_8,
	@SUM_TOTAL_9,
	@SUM_TOTAL_10,
	@SUM_TOTAL_11,
	@SUM_TOTAL_12,
	@SUM_TOTAL_13,
	@SUM_TOTAL_14,
	@SUM_TOTAL_15,
	0)
	
	SELECT * FROM @TEMP_ENERGY
	
END