/****** Object:  StoredProcedure [dbo].[GetCO2Year]    Script Date: 08/31/2014 21:53:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GetCO2Year]
AS
BEGIN
	--当年第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = CONVERT(VARCHAR(100),DATEADD(dd,1,DATEADD(mm,-MONTH(GETDATE()),GETDATE())) ,23)
	--获取当年的碳排量
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)*0.785
	FROM ConsumptionData C
	WHERE DeviceID=388 AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
	
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0
	
	SELECT @TOTAL
	
END
GO
/****** Object:  StoredProcedure [dbo].[GetCO2Mouth]    Script Date: 08/31/2014 21:57:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GetCO2Mouth]
AS
BEGIN
	--当月第一天
	DECLARE @DAY_MOUTH DATETIME
	SET @DAY_MOUTH = CONVERT(VARCHAR(100), DATEADD(dd,-DAY(GETDATE())+1,GETDATE()),23)
	--获取一个月的碳排量
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)*0.785
	FROM ConsumptionData C
	WHERE DeviceID=388 AND ReadingDate BETWEEN @DAY_MOUTH AND GETDATE()
	--过滤为空
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0
	SELECT @TOTAL
END
/****** Object:  StoredProcedure [dbo].[GetUtilities]    Script Date: 08/31/2014 21:58:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得今年的水电气
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilities]
	@DeviceID INT
AS
BEGIN
	--今年第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = CONVERT(VARCHAR(100),DATEADD(dd,1,DATEADD(mm,-MONTH(GETDATE()),GETDATE())) ,23)
	--获取水电气
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)
		FROM ConsumptionData C
		WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
		IF @TOTAL IS NULL
			SET @TOTAL = 0.0
		
	SELECT @TOTAL
		
END
GO
/****** Object:  StoredProcedure [dbo].[GetUtilitiesEnergy]    Script Date: 08/31/2014 21:58:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--能源消费明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesEnergy]
	@DeviceID INT
AS
BEGIN
	--今天
	DECLARE @DAY_TODAY DATETIME
	SET @DAY_TODAY = CONVERT(VARCHAR(100), DATEADD(dd,-DAY(GETDATE())+1,GETDATE()),23)
	--本周一
	DECLARE @DAY_WEEK DATETIME
	DECLARE @WEEKDAY INT
	SET @WEEKDAY = DATEPART(weekday,GETDATE())
	IF @WEEKDAY = 1
	BEGIN
		SET @DAY_WEEK = DATEADD(wk,DATEDIFF(wk,7,getdate()),0)    
	END
	ELSE
		SET @DAY_WEEK = DATEADD(wk,DATEDIFF(wk,0,GETDATE()),0)   
	--当月的第一天
	DECLARE @DAY_MONTH DATETIME
	SET @DAY_MONTH = DATEADD(mm, DATEDIFF(mm,0,DATEADD(mm, 0, GETDATE())), 0) 
	--当年的第一天
	DECLARE @DAY_YEAR DATETIME
	SET @DAY_YEAR = DATEADD(yy, DATEDIFF(yy,0,DATEADD(yy, 0, GETDATE())), 0)  	
	
	DECLARE @TOTAL_TODAY FLOAT
	DECLARE @TOTAL_WEEK FLOAT
	DECLARE @TOTAL_MONTH FLOAT
	DECLARE @TOTAL_YEAR FLOAT
	
	--Today
	SELECT @TOTAL_TODAY = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_TODAY AND GETDATE()
	IF @TOTAL_TODAY IS NULL
		SET @TOTAL_TODAY = 0
	--Week
	SELECT @TOTAL_WEEK = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_WEEK AND GETDATE()
	IF @TOTAL_WEEK IS NULL
		SET @TOTAL_WEEK = 0
	--Month
	SELECT @TOTAL_MONTH = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_MONTH AND GETDATE()
	IF @TOTAL_MONTH IS NULL
		SET @TOTAL_MONTH = 0
	--Year
	SELECT @TOTAL_YEAR = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR AND GETDATE()
	IF @TOTAL_YEAR IS NULL
		SET @TOTAL_YEAR = 0
		
	SELECT @TOTAL_TODAY AS 'Today',
	@TOTAL_WEEK AS 'WTD',
	@TOTAL_MONTH AS 'MTD',
	@TOTAL_YEAR AS 'YTD'
END
Go
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrev]    Script Date: 08/31/2014 21:58:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得去年的水电气
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrev]
	@DeviceID INT
AS
BEGIN
	--去年第一天
	DECLARE @DAY_YEAR_F DATETIME
	SET @DAY_YEAR_F = CONVERT(VARCHAR(100),DATEADD(dd,1,DATEADD(mm,-MONTH(GETDATE())-12,GETDATE())) ,23)
	--去年最后一天
	DECLARE @DAY_YEAR_L DATETIME
	SET @DAY_YEAR_L = DATEADD(ms,-3,DATEADD(yy, DATEDIFF(yy,0,getdate()), 0))  
	--获取水电气
	DECLARE @TOTAL FLOAT
	SELECT @TOTAL = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @DAY_YEAR_F AND @DAY_YEAR_L
	IF @TOTAL IS NULL
		SET @TOTAL = 0.0	
	SELECT @TOTAL
END
GO
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrevMonths]    Script Date: 08/31/2014 21:59:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得12个月的水电气明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrevMonths]
	@DeviceID INT
AS
BEGIN
	--获得每个月第一天和最后一天
	DECLARE @MOUTH_1_F DATETIME
	DECLARE @MOUTH_1_L DATETIME
	DECLARE @MOUTH_2_F DATETIME
	DECLARE @MOUTH_2_L DATETIME
	DECLARE @MOUTH_3_F DATETIME
	DECLARE @MOUTH_3_L DATETIME
	DECLARE @MOUTH_4_F DATETIME
	DECLARE @MOUTH_4_L DATETIME
	DECLARE @MOUTH_5_F DATETIME
	DECLARE @MOUTH_5_L DATETIME
	DECLARE @MOUTH_6_F DATETIME
	DECLARE @MOUTH_6_L DATETIME
	DECLARE @MOUTH_7_F DATETIME
	DECLARE @MOUTH_7_L DATETIME
	DECLARE @MOUTH_8_F DATETIME
	DECLARE @MOUTH_8_L DATETIME
	DECLARE @MOUTH_9_F DATETIME
	DECLARE @MOUTH_9_L DATETIME
	DECLARE @MOUTH_10_F DATETIME
	DECLARE @MOUTH_10_L DATETIME
	DECLARE @MOUTH_11_F DATETIME
	DECLARE @MOUTH_11_L DATETIME
	DECLARE @MOUTH_12_F DATETIME
	DECLARE @MOUTH_12_L DATETIME
	
	SET @MOUTH_1_F = CONVERT(VARCHAR(100),DATEADD(dd,1,DATEADD(mm,-MONTH(GETDATE())-12,GETDATE())) ,23)
	SET @MOUTH_2_F = DATEADD(mm,1,@MOUTH_1_F)
	SET @MOUTH_3_F = DATEADD(mm,2,@MOUTH_1_F)
	SET @MOUTH_4_F = DATEADD(mm,3,@MOUTH_1_F)
	SET @MOUTH_5_F = DATEADD(mm,4,@MOUTH_1_F)
	SET @MOUTH_6_F = DATEADD(mm,5,@MOUTH_1_F)
	SET @MOUTH_7_F = DATEADD(mm,6,@MOUTH_1_F)
	SET @MOUTH_8_F = DATEADD(mm,7,@MOUTH_1_F)
	SET @MOUTH_9_F = DATEADD(mm,8,@MOUTH_1_F)
	SET @MOUTH_10_F = DATEADD(mm,9,@MOUTH_1_F)
	SET @MOUTH_11_F = DATEADD(mm,10,@MOUTH_1_F)
	SET @MOUTH_12_F = DATEADD(mm,11,@MOUTH_1_F)
	SET @MOUTH_1_L = DATEADD(ms,-3,DATEADD(dd, DATEDIFF(dd,@MOUTH_1_F,@MOUTH_2_F), @MOUTH_1_F))
	SET @MOUTH_2_L = DATEADD(mm,1,@MOUTH_1_L)
	SET @MOUTH_3_L = DATEADD(mm,2,@MOUTH_1_L)
	SET @MOUTH_4_L = DATEADD(mm,3,@MOUTH_1_L)
	SET @MOUTH_5_L = DATEADD(mm,4,@MOUTH_1_L)
	SET @MOUTH_6_L = DATEADD(mm,5,@MOUTH_1_L)
	SET @MOUTH_7_L = DATEADD(mm,6,@MOUTH_1_L)
	SET @MOUTH_8_L = DATEADD(mm,7,@MOUTH_1_L)
	SET @MOUTH_9_L = DATEADD(mm,8,@MOUTH_1_L)
	SET @MOUTH_10_L = DATEADD(mm,9,@MOUTH_1_L)
	SET @MOUTH_11_L = DATEADD(mm,10,@MOUTH_1_L)
	SET @MOUTH_12_L = DATEADD(mm,11,@MOUTH_1_L)
	
	--获取每个月的水电气
	DECLARE @TOTAL_1 FLOAT
	SELECT @TOTAL_1 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_1_F AND @MOUTH_1_L
	IF @TOTAL_1 IS NULL
		SET @TOTAL_1 = 0.0
		
	DECLARE @TOTAL_2 FLOAT
	SELECT @TOTAL_2 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_2_F AND @MOUTH_2_L
	IF @TOTAL_2 IS NULL
		SET @TOTAL_2 = 0.0
	
	DECLARE @TOTAL_3 FLOAT
	SELECT @TOTAL_3 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_3_F AND @MOUTH_3_L
	IF @TOTAL_3 IS NULL
		SET @TOTAL_3 = 0.0
	
	DECLARE @TOTAL_4 FLOAT
	SELECT @TOTAL_4 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_4_F AND @MOUTH_4_L
	IF @TOTAL_4 IS NULL
		SET @TOTAL_4 = 0.0
			
	DECLARE @TOTAL_5 FLOAT
	SELECT @TOTAL_5 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_5_F AND @MOUTH_5_L
	IF @TOTAL_5 IS NULL
		SET @TOTAL_5 = 0.0
			
	DECLARE @TOTAL_6 FLOAT
	SELECT @TOTAL_6 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_6_F AND @MOUTH_6_L
	IF @TOTAL_6 IS NULL
		SET @TOTAL_6 = 0.0
	
	DECLARE @TOTAL_7 FLOAT
	SELECT @TOTAL_7 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_7_F AND @MOUTH_7_L
	IF @TOTAL_7 IS NULL
		SET @TOTAL_7 = 0.0
			
	DECLARE @TOTAL_8 FLOAT
	SELECT @TOTAL_8 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_8_F AND @MOUTH_8_L
	IF @TOTAL_8 IS NULL
		SET @TOTAL_8 = 0.0
	
	DECLARE @TOTAL_9 FLOAT
	SELECT @TOTAL_9 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_9_F AND @MOUTH_9_L
	IF @TOTAL_9 IS NULL
		SET @TOTAL_9 = 0.0
			
	DECLARE @TOTAL_10 FLOAT
	SELECT @TOTAL_10 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_10_F AND @MOUTH_10_L
	IF @TOTAL_10 IS NULL
		SET @TOTAL_10 = 0.0
	
	DECLARE @TOTAL_11 FLOAT
	SELECT @TOTAL_11 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_11_F AND @MOUTH_11_L
	IF @TOTAL_11 IS NULL
		SET @TOTAL_11 = 0.0
			
	DECLARE @TOTAL_12 FLOAT
	SELECT @TOTAL_12 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_12_F AND @MOUTH_12_L
	IF @TOTAL_12 IS NULL
		SET @TOTAL_12 = 0.0
	
	--Select		
	SELECT @TOTAL_1,
	@TOTAL_2,
	@TOTAL_3,
	@TOTAL_4,
	@TOTAL_5,
	@TOTAL_6,
	@TOTAL_7,
	@TOTAL_8,
	@TOTAL_9,
	@TOTAL_10,
	@TOTAL_11,
	@TOTAL_12 
END
/****** Object:  StoredProcedure [dbo].[GetUtilitiesPrevDays]    Script Date: 08/31/2014 21:58:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--获得12个月的水电气明细
--1.Electricity==388,2.Water==373,3.Gas==358,4.LN2==361
ALTER PROCEDURE [dbo].[GetUtilitiesPrevDays]
	@DeviceID	INT
AS
BEGIN
	--获得每个月第一天和最后一天
	DECLARE @MOUTH_1_F DATETIME
	DECLARE @MOUTH_1_L DATETIME
	DECLARE @MOUTH_2_F DATETIME
	DECLARE @MOUTH_2_L DATETIME
	DECLARE @MOUTH_3_F DATETIME
	DECLARE @MOUTH_3_L DATETIME
	DECLARE @MOUTH_4_F DATETIME
	DECLARE @MOUTH_4_L DATETIME
	DECLARE @MOUTH_5_F DATETIME
	DECLARE @MOUTH_5_L DATETIME
	DECLARE @MOUTH_6_F DATETIME
	DECLARE @MOUTH_6_L DATETIME
	DECLARE @MOUTH_7_F DATETIME
	DECLARE @MOUTH_7_L DATETIME
	DECLARE @MOUTH_8_F DATETIME
	DECLARE @MOUTH_8_L DATETIME
	DECLARE @MOUTH_9_F DATETIME
	DECLARE @MOUTH_9_L DATETIME
	DECLARE @MOUTH_10_F DATETIME
	DECLARE @MOUTH_10_L DATETIME
	DECLARE @MOUTH_11_F DATETIME
	DECLARE @MOUTH_11_L DATETIME
	DECLARE @MOUTH_12_F DATETIME
	DECLARE @MOUTH_12_L DATETIME
	
	SET @MOUTH_1_F = CONVERT(VARCHAR(100),DATEADD(dd,1,DATEADD(mm,-MONTH(GETDATE())-12,GETDATE())) ,23)
	SET @MOUTH_2_F = DATEADD(mm,1,@MOUTH_1_F)
	SET @MOUTH_3_F = DATEADD(mm,2,@MOUTH_1_F)
	SET @MOUTH_4_F = DATEADD(mm,3,@MOUTH_1_F)
	SET @MOUTH_5_F = DATEADD(mm,4,@MOUTH_1_F)
	SET @MOUTH_6_F = DATEADD(mm,5,@MOUTH_1_F)
	SET @MOUTH_7_F = DATEADD(mm,6,@MOUTH_1_F)
	SET @MOUTH_8_F = DATEADD(mm,7,@MOUTH_1_F)
	SET @MOUTH_9_F = DATEADD(mm,8,@MOUTH_1_F)
	SET @MOUTH_10_F = DATEADD(mm,9,@MOUTH_1_F)
	SET @MOUTH_11_F = DATEADD(mm,10,@MOUTH_1_F)
	SET @MOUTH_12_F = DATEADD(mm,11,@MOUTH_1_F)
	SET @MOUTH_1_L = DATEADD(ms,-3,DATEADD(dd, DATEDIFF(dd,@MOUTH_1_F,@MOUTH_2_F), @MOUTH_1_F))
	SET @MOUTH_2_L = DATEADD(mm,1,@MOUTH_1_L)
	SET @MOUTH_3_L = DATEADD(mm,2,@MOUTH_1_L)
	SET @MOUTH_4_L = DATEADD(mm,3,@MOUTH_1_L)
	SET @MOUTH_5_L = DATEADD(mm,4,@MOUTH_1_L)
	SET @MOUTH_6_L = DATEADD(mm,5,@MOUTH_1_L)
	SET @MOUTH_7_L = DATEADD(mm,6,@MOUTH_1_L)
	SET @MOUTH_8_L = DATEADD(mm,7,@MOUTH_1_L)
	SET @MOUTH_9_L = DATEADD(mm,8,@MOUTH_1_L)
	SET @MOUTH_10_L = DATEADD(mm,9,@MOUTH_1_L)
	SET @MOUTH_11_L = DATEADD(mm,10,@MOUTH_1_L)
	SET @MOUTH_12_L = DATEADD(mm,11,@MOUTH_1_L)
	
	--获取每个月的水电气
	DECLARE @TOTAL_1 FLOAT
	SELECT @TOTAL_1 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_1_F AND @MOUTH_1_L
	IF @TOTAL_1 IS NULL
		SET @TOTAL_1 = 0.0
		
	DECLARE @TOTAL_2 FLOAT
	SELECT @TOTAL_2 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_2_F AND @MOUTH_2_L
	IF @TOTAL_2 IS NULL
		SET @TOTAL_2 = 0.0
	
	DECLARE @TOTAL_3 FLOAT
	SELECT @TOTAL_3 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_3_F AND @MOUTH_3_L
	IF @TOTAL_3 IS NULL
		SET @TOTAL_3 = 0.0
	
	DECLARE @TOTAL_4 FLOAT
	SELECT @TOTAL_4 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_4_F AND @MOUTH_4_L
	IF @TOTAL_4 IS NULL
		SET @TOTAL_4 = 0.0
			
	DECLARE @TOTAL_5 FLOAT
	SELECT @TOTAL_5 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_5_F AND @MOUTH_5_L
	IF @TOTAL_5 IS NULL
		SET @TOTAL_5 = 0.0
			
	DECLARE @TOTAL_6 FLOAT
	SELECT @TOTAL_6 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_6_F AND @MOUTH_6_L
	IF @TOTAL_6 IS NULL
		SET @TOTAL_6 = 0.0
	
	DECLARE @TOTAL_7 FLOAT
	SELECT @TOTAL_7 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_7_F AND @MOUTH_7_L
	IF @TOTAL_7 IS NULL
		SET @TOTAL_7 = 0.0
			
	DECLARE @TOTAL_8 FLOAT
	SELECT @TOTAL_8 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_8_F AND @MOUTH_8_L
	IF @TOTAL_8 IS NULL
		SET @TOTAL_8 = 0.0
	
	DECLARE @TOTAL_9 FLOAT
	SELECT @TOTAL_9 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_9_F AND @MOUTH_9_L
	IF @TOTAL_9 IS NULL
		SET @TOTAL_9 = 0.0
			
	DECLARE @TOTAL_10 FLOAT
	SELECT @TOTAL_10 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_10_F AND @MOUTH_10_L
	IF @TOTAL_10 IS NULL
		SET @TOTAL_10 = 0.0
	
	DECLARE @TOTAL_11 FLOAT
	SELECT @TOTAL_11 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_11_F AND @MOUTH_11_L
	IF @TOTAL_11 IS NULL
		SET @TOTAL_11 = 0.0
			
	DECLARE @TOTAL_12 FLOAT
	SELECT @TOTAL_12 = SUM(C.Value)
	FROM ConsumptionData C
	WHERE DeviceID=@DeviceID AND ReadingDate BETWEEN @MOUTH_12_F AND @MOUTH_12_L
	IF @TOTAL_12 IS NULL
		SET @TOTAL_12 = 0.0
	
	--Select		
	SELECT @TOTAL_1,
	@TOTAL_2,
	@TOTAL_3,
	@TOTAL_4,
	@TOTAL_5,
	@TOTAL_6,
	@TOTAL_7,
	@TOTAL_8,
	@TOTAL_9,
	@TOTAL_10,
	@TOTAL_11,
	@TOTAL_12 
END